WORKDIR: /tmp/workdir

KAFKA_BINARY_NAME: amq-streams-1.5.0-bin.zip
PROMETHEUS_BINARY_URL: https://github.com/prometheus/prometheus/releases/download/v2.20.1/prometheus-2.20.1.darwin-amd64.tar.gz
JMX_EXPORTER_URL: https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.13.0/jmx_prometheus_javaagent-0.13.0.jar
JOLOKIA_BINARY_URL: https://search.maven.org/remotecontent?filepath=org/jolokia/jolokia-jvm/1.6.2/jolokia-jvm-1.6.2-agent.jar
KAFKA_EXPORTER_URL: https://github.com/danielqsj/kafka_exporter/releases/download/v1.2.0/kafka_exporter-1.2.0.darwin-amd64.tar.gz
NODE_EXPORTER_URL: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.darwin-amd64.tar.gz
GRAFANA_BINARY_URL: https://dl.grafana.com/oss/release/grafana-7.1.3.darwin-amd64.tar.gz
ALERT_MANAGER_BINARY_URL: https://github.com/prometheus/alertmanager/releases/download/v0.21.0/alertmanager-0.21.0.darwin-amd64.tar.gz

ZOOKEEPER_MONITORING: true
KAFKA_MONITORING: true
KAFKA_EXPORTER: true
NODE_EXPORTER: true
CONSUMER_MONITORING: true
PRODUCER_MONITORING: true
GRAFANA_MONITORING: true

PROMETHEUS: true
GRAFANA: true
ALERT_MANAGER: true